add_child:
  name: Add Child
  description: Add a child to Baby Buddy
  fields:
    first_name:
      name: First Name
      description: Child's first name
      required: true
      selector:
        text:
    last_name:
      name: Last Name
      description: Child's last name
      required: true
      selector:
        text:
    birth_date:
      name: Birth Date
      description: Child's birth date in YYYY-MM-DD format
      required: true
      selector:
        text:

start_timer:
  name: Start Timer
  description: Start a new timer
  target:
    entity:
      integration: babybuddy
      domain: switch
  fields:
    start:
      name: Timer start time
      description: Leave blank for a quick start
      selector:
        time:
    name:
      name: Timer name
      description: Specify optional timer name
      selector:
        text:

add_feeding:
  name: Add Feeding
  description: Adds a feeding entry
  target:
    entity:
      integration: babybuddy
      domain: switch
  fields:
    timer:
      name: Use timer
      description: Use active timer to assign child/start/end
      selector:
        boolean:
    start:
      name: Feeding start time
      description: Feeding start time
      selector:
        time:
    end:
      name: Feeding end time
      description: Feeding end time
      selector:
        time:
    type:
      name: Feeding type
      description: Feeding type
      required: true
      selector:
        select:
          options:
            - Breast milk
            - Formula
            - Fortified breast milk
            - Solid food
    method:
      name: Feeding method
      description: Feeding method
      required: true
      selector:
        select:
          options:
            - Bottle
            - Left breast
            - Right breast
            - Both breasts
            - Parent fed
            - Self fed
    amount:
      name: Feeding amount
      description: Feeding amount in number format
      selector:
        number:
          min: 1
          max: 300
          mode: box
    notes:
      name: Feeding notes
      description: Feeding notes
      selector:
        text:
          multiline: true

add_sleep:
  name: Add Sleep
  description: Adds sleep entry
  target:
    entity:
      integration: babybuddy
      domain: switch
  fields:
    timer:
      name: Use timer
      description: Use active timer to assign child/start/end
      selector:
        boolean:
    start:
      name: Sleep start time
      description: Sleep start time
      selector:
        time:
    end:
      name: Sleep end time
      description: Sleep end time
      selector:
        time:
    notes:
      name: Sleep notes
      description: Sleep notes
      selector:
        text:
          multiline: true

add_tummy_time:
  name: Add Tummy Time
  description: Adds Tummy Time entry
  target:
    entity:
      integration: babybuddy
      domain: switch
  fields:
    timer:
      name: Use timer
      description: Use active timer to assign child/start/end
      selector:
        boolean:
    start:
      name: Sleep start time
      description: Sleep start time
      selector:
        time:
    end:
      name: Sleep end time
      description: Sleep end time
      selector:
        time:
    milestone:
      name: Tummy Time milestone
      description: Tummy Time milestone
      selector:
        text:
          multiline: true

add_diaper_change:
  name: Add diaper change
  description: Adds a diaper change entry
  target:
    entity:
      integration: babybuddy
      domain: sensor
      device_class: babybuddy__child
  fields:
    time:
      name: Change time
      description: Change time
      selector:
        time:
    type:
      name: Diaper type
      description: Type of diaper change
      required: true
      default: wet
      selector:
        select:
          options:
            - Wet
            - Solid
            - Wet and Solid
    color:
      name: Diaper color
      description: Diaper color
      selector:
        select:
          options:
            - Black
            - Brown
            - Green
            - Yellow
    amount:
      name: Diaper change amount
      description: Diaper change amount
      selector:
        number:
          min: 1
          max: 10
          mode: box
    notes:
      name: Change notes
      description: Change notes
      selector:
        text:
          multiline: true

add_temperature:
  name: Add Temperature
  description: Adds a temperature entry
  target:
    entity:
      integration: babybuddy
      domain: sensor
      device_class: babybuddy__child
  fields:
    temperature:
      name: Temperature
      description: Temperature
      required: true
      selector:
        number:
          min: 35.0
          max: 150.0
          step: 0.1
          mode: box
    time:
      name: Temperature time
      description: Temperature time
      selector:
        time:
    notes:
      name: Temperature notes
      description: Temperature notes
      selector:
        text:
          multiline: true

add_weight:
  name: Add Weight
  description: Adds a weight entry
  target:
    entity:
      integration: babybuddy
      domain: sensor
      device_class: babybuddy__child
  fields:
    weight:
      name: Weight
      description: Weight value
      required: true
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 0.1
          mode: box
    date:
      name: Weight date
      description: Weight date in YYYY-MM-DD format
      selector:
        text:
    notes:
      name: Weight notes
      description: Weight notes
      selector:
        text:
          multiline: true

add_note:
  name: Add Note
  description: Adds a note entry
  target:
    entity:
      integration: babybuddy
      domain: sensor
      device_class: babybuddy__child
  fields:
    note:
      name: Note
      description: Note text
      required: true
      selector:
        text:
          multiline: true
    time:
      name: Note time
      description: Note time
      selector:
        time:

delete_last_entry:
  name: Delete last Babybuddy entry
  description: Delete the last babybuddy sensor entry
  target:
    entity:
      integration: babybuddy
      domain: sensor
